### ISSUE TITLE
Responsive grid on data types page

### ISSUE THREAD

**Issue by steeltoedsneakr** [OPCNZ/priv-o-matic#10]
The current page isn't completely optimised for mobile, and the items become difficult to read on small screens.

Ideally needs to be single line options on small screen, rather than 1-2.

I've tried to get a build to work using "pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2" etc. but not having any luck.

app/templates/components/step-data-types.hbs

**Comment by ss23** [comment]
I have a pull request for this incoming. The responsive grid isn't included with the base pure ember package, but bower pulls it in, so we can just specify it in Brocfile. :boom:
